PRODUCT_PACKAGES += \
    a_goodix.b00 \
    a_goodix.b01 \
    a_goodix.b02 \
    a_goodix.b03 \
    a_goodix.b04 \
    a_goodix.b05 \
    a_goodix.b06 \
    a_goodix.b07 \
    a_goodix.mdt \
    b_goodix.b00 \
    b_goodix.b01 \
    b_goodix.b02 \
    b_goodix.b03 \
    b_goodix.b04 \
    b_goodix.b05 \
    b_goodix.b06 \
    b_goodix.b07 \
    b_goodix.mdt \
