include $(CLEAR_VARS)
LOCAL_MODULE       := $(SINGLE_TARGET)
LOCAL_MODULE_TAGS  := $(SINGLE_MODULE_TAGS)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/firmware
LOCAL_SRC_FILES    := $(SINGLE_TARGET)
include $(BUILD_PREBUILT)